/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package prjestructurag5;
import javax.swing.JOptionPane;
import vistasM1.*;
/**
 *
 * @author Derek
 */
public class JF_menuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JF_menuPrincipal
     */
    public JF_menuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ico_UsuariosM1 = new javax.swing.JLabel();
        jlb_facturacion = new javax.swing.JLabel();
        TITULO = new javax.swing.JLabel();
        ico_facturacionM4 = new javax.swing.JLabel();
        ico_ventasM3 = new javax.swing.JLabel();
        jlb_usuario1 = new javax.swing.JLabel();
        jlb_facturacion1 = new javax.swing.JLabel();
        ico_eventosM2 = new javax.swing.JLabel();
        jlb_usuario2 = new javax.swing.JLabel();
        ico_cerrarSesion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ico_parlantes64.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, -1));

        ico_UsuariosM1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ico_usuarios128.png"))); // NOI18N
        ico_UsuariosM1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ico_UsuariosM1MouseClicked(evt);
            }
        });
        jPanel1.add(ico_UsuariosM1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));

        jlb_facturacion.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jlb_facturacion.setForeground(new java.awt.Color(0, 0, 0));
        jlb_facturacion.setText("CAJAS");
        jPanel1.add(jlb_facturacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 480, -1, -1));

        TITULO.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        TITULO.setForeground(new java.awt.Color(0, 0, 0));
        TITULO.setText("MULTIFIESTAS");
        jPanel1.add(TITULO, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        ico_facturacionM4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ico_cajas128.png"))); // NOI18N
        ico_facturacionM4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ico_facturacionM4MouseClicked(evt);
            }
        });
        jPanel1.add(ico_facturacionM4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, 130, 130));

        ico_ventasM3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ico_facturacion128.png"))); // NOI18N
        ico_ventasM3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ico_ventasM3MouseClicked(evt);
            }
        });
        jPanel1.add(ico_ventasM3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, -1, -1));

        jlb_usuario1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jlb_usuario1.setForeground(new java.awt.Color(0, 0, 0));
        jlb_usuario1.setText("EVENTOS");
        jPanel1.add(jlb_usuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, -1, -1));

        jlb_facturacion1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jlb_facturacion1.setForeground(new java.awt.Color(0, 0, 0));
        jlb_facturacion1.setText("FACTURACION");
        jPanel1.add(jlb_facturacion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 480, -1, -1));

        ico_eventosM2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ico_eventos128.png"))); // NOI18N
        ico_eventosM2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ico_eventosM2MouseClicked(evt);
            }
        });
        jPanel1.add(ico_eventosM2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, -1, -1));

        jlb_usuario2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jlb_usuario2.setForeground(new java.awt.Color(0, 0, 0));
        jlb_usuario2.setText("REGISTRO USUARIOS");
        jPanel1.add(jlb_usuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, -1));

        ico_cerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ico_cerrarSesion32.png"))); // NOI18N
        ico_cerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ico_cerrarSesionMouseClicked(evt);
            }
        });
        jPanel1.add(ico_cerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ico_UsuariosM1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ico_UsuariosM1MouseClicked
        // TODO add your handling code here:
        dispose();
        new JF_menuM1().setVisible(true);
    }//GEN-LAST:event_ico_UsuariosM1MouseClicked

    private void ico_eventosM2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ico_eventosM2MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "MODULO NO DISPONIBLE");
    }//GEN-LAST:event_ico_eventosM2MouseClicked

    private void ico_ventasM3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ico_ventasM3MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "MODULO NO DISPONIBLE");
    }//GEN-LAST:event_ico_ventasM3MouseClicked

    private void ico_facturacionM4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ico_facturacionM4MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "MODULO NO DISPONIBLE");
    }//GEN-LAST:event_ico_facturacionM4MouseClicked

    private void ico_cerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ico_cerrarSesionMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "ESTO CERRARIA LA SESION PERO NO ESTA HECHO XD");
    }//GEN-LAST:event_ico_cerrarSesionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_menuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_menuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_menuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_menuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_menuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TITULO;
    private javax.swing.JLabel ico_UsuariosM1;
    private javax.swing.JLabel ico_cerrarSesion;
    private javax.swing.JLabel ico_eventosM2;
    private javax.swing.JLabel ico_facturacionM4;
    private javax.swing.JLabel ico_ventasM3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlb_facturacion;
    private javax.swing.JLabel jlb_facturacion1;
    private javax.swing.JLabel jlb_usuario1;
    private javax.swing.JLabel jlb_usuario2;
    // End of variables declaration//GEN-END:variables
}
